version: "3"

services:
  nginx:
    stdin_open: true
    tty: true
    restart: always
    build:
      context: ./requirements/nginx/
    ports:
      - 443:443
    container_name: nginx
    tmpfs:
      - /tmp
      - /run
    privileged: true
    depends_on:
      - wordpress
    networks:
      - nginx_wordpress

  mariadb:
    stdin_open: true
    tty: true
    restart: always
    build:
      context: ./requirements/mariadb/
    ports:
      - 3306:3306
    container_name: mariadb
    tmpfs:
      - /tmp
      - /run
    privileged: true

  wordpress:
    stdin_open: true
    tty: true
    restart: always
    build:
      context: ./requirements/wordpress/
    # ports:
    #   - 9000:9000
    container_name: wordpress
    networks:
      - nginx_wordpress
    # tmpfs:
    #   - /tmp
    #   - /run
    # privileged: true

networks:
  nginx_wordpress:
