version: "3"

services:
  nginx:
    stdin_open: true
    tty: true
    restart: always
    image: nginx
    build:
      context: ./requirements/nginx/
    ports:
      - 443:443
    container_name: nginx
    tmpfs:
      - /tmp
      - /run
    privileged: true
    depends_on:
      wordpress:
        condition: service_healthy
      rust:
        condition: service_healthy
      adminer:
        condition: service_healthy
    networks:
      - nginx_wordpress
      - nginx_rust
      - nginx_adminer
      - nginx_exporter
      - nginx_k6
    volumes:
      - wordpress-volume:/var/www/html/wordpress/
    healthcheck:
      test: ["CMD", "curl", "-k", "--silent", "https://localhost:443/"]
      interval: 2s
      timeout: 30s
      retries: 3

  mariadb:
    stdin_open: true
    tty: true
    restart: always
    image: mariadb
    build:
      context: ./requirements/mariadb/
    container_name: mariadb
    tmpfs:
      - /tmp
      - /run
    privileged: true
    networks:
      - wordpress_mariadb
      - adminer_mariadb
    volumes:
      - wordpress-db-volume:/var/lib/mysql/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 2s
      timeout: 30s
      retries: 3

  wordpress:
    stdin_open: true
    tty: true
    restart: always
    image: wordpress
    build:
      context: ./requirements/wordpress/
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - wordpress_mariadb
      - nginx_wordpress
      - wordpress_redis
    volumes:
      - wordpress-volume:/var/www/html/wordpress/
    tmpfs:
      - /tmp
      - /run
    privileged: true
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm"]
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 60s

  rust:
    stdin_open: true
    tty: true
    restart: always
    image: rust
    build:
      context: ./requirements/rust/
    container_name: rust
    networks:
      - nginx_rust
    tmpfs:
      - /tmp
      - /run
    privileged: true
    healthcheck:
      test: ["CMD", "curl", "--silent", "http://127.0.0.1:4000/"]
      interval: 2s
      timeout: 30s
      retries: 3

  redis:
    stdin_open: true
    tty: true
    restart: always
    image: redis
    build:
      context: ./requirements/redis/
    container_name: redis
    tmpfs:
      - /tmp
      - /run
    privileged: true
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 30s
      retries: 3
    networks:
      - wordpress_redis

  adminer:
    stdin_open: true
    tty: true
    restart: always
    image: adminer
    build:
      context: ./requirements/adminer/
    container_name: adminer
    networks:
      - nginx_adminer
      - adminer_mariadb
    tmpfs:
      - /tmp
      - /run
    privileged: true
    healthcheck:
      test: ["CMD", "curl", "--silent", "http://127.0.0.1:5000/"]
      interval: 2s
      timeout: 30s
      retries: 3

  ftp:
    stdin_open: true
    tty: true
    restart: always
    image: ftp
    build:
      context: ./requirements/ftp/
      args:
        - FTP_USER=$FTP_USER
        - FTP_PASSWORD=$FTP_PASSWORD
    container_name: ftp
    tmpfs:
      - /tmp
      - /run
    privileged: true
    ports:
      - 21:21
      - 10000-10100:10000-10100
    healthcheck:
      test: ["CMD", "ftp", "localhost"]
      interval: 2s
      timeout: 30s
      retries: 3
    volumes:
      - wordpress-volume:/var/www/html/

  exporter:
    stdin_open: true
    tty: true
    restart: always
    image: exporter
    build:
      context: ./requirements/exporter/
    container_name: exporter
    tmpfs:
      - /tmp
      - /run
    privileged: true
    networks:
      - nginx_exporter
      - exporter_prometheus
    depends_on:
      nginx:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9113/metrics"]
      interval: 2s
      timeout: 30s
      retries: 3

  prometheus:
    stdin_open: true
    tty: true
    restart: always
    image: prometheus
    build:
      context: ./requirements/prometheus/
    container_name: prometheus
    tmpfs:
      - /tmp
      - /run
    privileged: true
    networks:
      - exporter_prometheus
      - grafana_prometheus
    depends_on:
      exporter:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--silent", "http://localhost:9090"]
      interval: 2s
      timeout: 30s
      retries: 3

  grafana:
    stdin_open: true
    tty: true
    restart: always
    image: grafana
    build:
      context: ./requirements/grafana/
    container_name: grafana
    tmpfs:
      - /tmp
      - /run
    privileged: true
    depends_on:
      prometheus:
        condition: service_healthy
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "--silent", "http://localhost:3000/login"]
      interval: 2s
      timeout: 30s
      retries: 3
    networks:
      - grafana_prometheus

  k6:
    stdin_open: true
    tty: true
    restart: always
    image: k6
    build:
      context: ./requirements/k6/
    container_name: k6
    tmpfs:
      - /tmp
      - /run
    privileged: true
    depends_on:
      nginx:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-k", "--silent", "https://nginx:443/"]
      interval: 2s
      timeout: 30s
      retries: 3
    networks:
      - nginx_k6

networks:
  wordpress_mariadb:
  nginx_wordpress:
  nginx_rust:
  wordpress_redis:
  nginx_adminer:
  adminer_mariadb:
  nginx_exporter:
  exporter_prometheus:
  grafana_prometheus:
  nginx_k6:

volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  wordpress-db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
