version: "3"

services:
  nginx:
    stdin_open: true
    tty: true
    restart: always
    build:
      context: ./requirements/nginx/
    ports:
      - 443:443
    container_name: nginx
    tmpfs:
      - /tmp
      - /run
    privileged: true
    depends_on:
      - wordpress
    networks:
      - nginx_wordpress
    volumes:
      - wordpress-volume:/var/www/html/wordpress/

  mariadb:
    stdin_open: true
    tty: true
    restart: always
    build:
      context: ./requirements/mariadb/
    container_name: mariadb
    tmpfs:
      - /tmp
      - /run
    privileged: true
    networks:
      - wordpress_mariadb
    volumes:
      - wordpress-db-volume:/var/lib/mysql/

  wordpress:
    stdin_open: true
    tty: true
    restart: always
    build:
      context: ./requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - wordpress_mariadb
      - nginx_wordpress
    volumes:
      - wordpress-volume:/var/www/html/wordpress/
    tmpfs:
      - /tmp
      - /run
    privileged: true

networks:
  wordpress_mariadb:
  nginx_wordpress:

volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  wordpress-db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
