version: "3"

services:
  nginx:
    stdin_open: true
    tty: true
    restart: always
    image: nginx
    build:
      context: ./requirements/nginx/
    ports:
      - 443:443
    container_name: nginx
    tmpfs:
      - /tmp
      - /run
    privileged: true
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - nginx_wordpress
    volumes:
      - wordpress-volume:/var/www/html/wordpress/

  mariadb:
    stdin_open: true
    tty: true
    restart: always
    image: mariadb
    build:
      context: ./requirements/mariadb/
    container_name: mariadb
    tmpfs:
      - /tmp
      - /run
    privileged: true
    networks:
      - wordpress_mariadb
    volumes:
      - wordpress-db-volume:/var/lib/mysql/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 1s
      timeout: 10s
      retries: 10

  wordpress:
    stdin_open: true
    tty: true
    restart: always
    image: wordpress
    build:
      context: ./requirements/wordpress/
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - wordpress_mariadb
      - nginx_wordpress
    volumes:
      - wordpress-volume:/var/www/html/wordpress/
    tmpfs:
      - /tmp
      - /run
    privileged: true
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm"]
      interval: 1s
      timeout: 10s
      retries: 10

networks:
  wordpress_mariadb:
  nginx_wordpress:

volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  wordpress-db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
