version: "3"

services:
  nginx:
    stdin_open: true
    tty: true
    restart: always
    image: nginx
    build:
      context: ./requirements/nginx/
    ports:
      - 443:443
    container_name: nginx
    tmpfs:
      - /tmp
      - /run
    privileged: true
    depends_on:
      wordpress:
        condition: service_healthy
      rust:
        condition: service_healthy
      adminer:
        condition: service_healthy
    networks:
      - nginx_wordpress
      - nginx_rust
      - nginx_adminer
    volumes:
      - wordpress-volume:/var/www/html/wordpress/
    healthcheck:
      test: ["CMD", "curl", "--silent", "https://127.0.0.1/"]
      interval: 1s
      timeout: 10s
      retries: 10

  mariadb:
    stdin_open: true
    tty: true
    restart: always
    image: mariadb
    build:
      context: ./requirements/mariadb/
    container_name: mariadb
    tmpfs:
      - /tmp
      - /run
    privileged: true
    networks:
      - wordpress_mariadb
      - adminer_mariadb
    volumes:
      - wordpress-db-volume:/var/lib/mysql/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 1s
      timeout: 10s
      retries: 10

  wordpress:
    stdin_open: true
    tty: true
    restart: always
    image: wordpress
    build:
      context: ./requirements/wordpress/
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - wordpress_mariadb
      - nginx_wordpress
      - wordpress_redis
    volumes:
      - wordpress-volume:/var/www/html/wordpress/
    tmpfs:
      - /tmp
      - /run
    privileged: true
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm"]
      interval: 1s
      timeout: 10s
      retries: 10

  rust:
    stdin_open: true
    tty: true
    restart: always
    image: rust
    build:
      context: ./requirements/rust/
    container_name: rust
    networks:
      - nginx_rust
    tmpfs:
      - /tmp
      - /run
    privileged: true
    healthcheck:
      test: ["CMD", "curl", "--silent", "http://127.0.0.1:3000/"]
      interval: 1s
      timeout: 10s
      retries: 10

  redis:
    stdin_open: true
    tty: true
    restart: always
    image: redis
    build:
      context: ./requirements/redis/
    container_name: redis
    tmpfs:
      - /tmp
      - /run
    privileged: true
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 10s
      retries: 10
    networks:
      - wordpress_redis

  adminer:
    stdin_open: true
    tty: true
    restart: always
    image: adminer
    build:
      context: ./requirements/adminer/
    container_name: adminer
    networks:
      - nginx_adminer
      - adminer_mariadb
    tmpfs:
      - /tmp
      - /run
    privileged: true
    healthcheck:
      test: ["CMD", "curl", "--silent", "http://127.0.0.1:5000/"]
      interval: 1s
      timeout: 10s
      retries: 10

  ftp:
    stdin_open: true
    tty: true
    restart: always
    image: ftp
    build:
      context: ./requirements/ftp/
    container_name: ftp
    tmpfs:
      - /tmp
      - /run
    privileged: true
    ports:
      - 21:21
      - 10000-10100:10000-10100
    healthcheck:
      test: ["CMD", "telnet", "localhost", "21"]
      interval: 1s
      timeout: 10s
      retries: 10
    volumes:
      - wordpress-volume:/var/www/html/


networks:
  wordpress_mariadb:
  nginx_wordpress:
  nginx_rust:
  wordpress_redis:
  nginx_adminer:
  adminer_mariadb:

volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  wordpress-db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
