version: "3"

services:
  nginx:
    stdin_open: true
    tty: true
    restart: always
    build:
      context: ./requirements/nginx/
    ports:
      - 443:443
    container_name: nginx

  # mariadb:
  #   stdin_open: true
  #   tty: true
  #   build:
  #     context: ./requirements/mariadb/
  #   container_name: mariadb
