version: '3'

services:
  db:
    image: mariadb:latest
    volumes:
      - mysql-vol:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password1234
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      mynet:
        ipv4_address: 172.20.0.3

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wp-vol:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    ports:
      - "8000:80"
    networks:
      mynet:
        ipv4_address: 172.20.0.2

volumes:
  mysql-vol:
    driver_opts:
      type: none
      device: /data/mysql
      o: bind
  wp-vol:
    driver_opts:
      type: none
      device: /data/html
      o: bind

networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
