version: "3"

services:
  mysql_container:
    image: mysql:8.0
    networks:
      - wordpress_network
    volumes:
      - mysql_volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: wordpress000db
      MYSQL_USER: wordpress000kun
      MYSQL_PASSWORD: wkunpass

  wordpress_container:
    depends_on:
      - mysql_container
    image: wordpress
    networks:
      - wordpress_network
    volumes:
      - wordpress_volume:/var/www/html
    ports:
      - 8082:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql_container
      WORDPRESS_DB_NAME: wordpress000db
      WORDPRESS_DB_USER: wordpress000kun
      WORDPRESS_DB_PASSWORD: wkunpass


networks:
  wordpress_network:
volumes:
  mysql_volume:
  wordpress_volume:
