# docker build -t ${IMAGE_NAME} .
# docker run --name ${CONTAINER_NAME} -d -v $PWD/${DATA_DIR}:/var/lib/mysql -p ${HOST_PORT}:3306 ${IMAGE_NAME}
# docker exec -it ${CONTAINER_NAME} /bin/bash


FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD rootpass
ENV MYSQL_DATABASE test
ENV MYSQL_USER testuser
ENV MYSQL_PASSWORD testpass

COPY ./my.conf /etc/mysql/conf.d/my.cnf
