# sudo docker-compose up -d
# docker exec -it nvim_tmux tmux

version: "3"
services:
  lvim-tmux:
    stdin_open: true
    tty: true
    build:
      context: .
      args:
        USER: ${USER}
    volumes:
      - /home/${USER}:/home/${USER}/dev
    container_name: lvim-tmux
    env_file: .env
    environment:
      - USER=${USER}
    command: tmux
