# ~/.config/starship.toml

format = """
$directory\
[](fg:#9A348E bg:#06969A)\
$git_branch\
$git_status\
[ ](fg:#06969A)\
$status\
\n\
$character\
"""

[directory]
style = "bg:#9A348E"
format = "[ $path ]($style)"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#06969A"
format = '[$all_status$ahead_behind ]($style)'
deleted = '󰅖'

[status]
disabled = false
symbol = ' '
